// Shared return type interfaces for all k8s API handlers.
// Each exported async function in the handlers/ directory uses one of these types.
// Canonical definitions live in src/shared/k8s.ts so main and renderer can't drift apart.

export type {
  ApplyResult,
  ClusterRoleBindingInfo,
  ClusterRoleInfo,
  Condition,
  ConfigMapInfo,
  ContainerInfo,
  ContextInfo,
  CronJobInfo,
  DaemonSetInfo,
  DeploymentInfo,
  DeploymentRevision,
  EndpointAddress,
  EndpointInfo,
  EndpointPortInfo,
  EndpointSubset,
  EventInfo,
  HelmRelease,
  HelmRepo,
  HPAInfo,
  HPAMetric,
  IngressInfo,
  IngressPathInfo,
  IngressRuleInfo,
  IngressTLSInfo,
  JobInfo,
  LimitRangeInfo,
  LimitRangeLimit,
  MetricsUnavailable,
  MutationResult,
  NamespaceInfo,
  NetworkPolicyInfo,
  NetworkPolicyPeer,
  NetworkPolicyPortInfo,
  NetworkPolicyRule,
  NodeInfo,
  NodeMetric,
  PDBInfo,
  PodContainerInfo,
  PodInfo,
  PVCInfo,
  PVClaimRef,
  PVInfo,
  RbacRule,
  RbacSubject,
  ReplicaSetInfo,
  ResourceQuotaInfo,
  ResourceRef,
  RoleBindingInfo,
  RoleInfo,
  SecretInfo,
  ServiceAccountInfo,
  ServiceInfo,
  ServicePortInfo,
  StatefulSetInfo,
  UpdateClusterRoleBindingResult,
  UpdateClusterRoleResult,
  UpdateRoleBindingResult,
  UpdateRoleResult,
  UpdateServiceAccountResult,
} from "../../shared/k8s"
