name: action.ci
on:
  push:
    paths:
      - "src/**"
      - .github/workflows/action.yaml

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: module caching
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{runner.OS}}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}
      
      - name: install
        run: npm install

      - name: lint
        run: rpm run lint
